// Generated by Scapix Language Bridge
// https://www.scapix.com

package com.scapix.chat;

public abstract class AbstructElement extends com.scapix.Bridge
{
	public native void func1();
	public native void func2();
	public native void func3();

	protected AbstructElement(Nop nop) { super(nop); }
	static { System.loadLibrary("chatlib"); }
}
