// Generated by Scapix Language Bridge
// https://www.scapix.com

package com.scapix.chat;

public class Contact extends com.scapix.Bridge
{
	@FunctionalInterface
	public static interface Function0
	{
		void call(java.lang.String p1);
	}

	public Contact() { super(nop); _init(); }
	public Contact(java.lang.String id, java.lang.String name) { super(nop); _init(id, name); }

	public native java.lang.String deviceName();
	public native java.lang.String id();
	public native void id(java.lang.String id);
	public native java.lang.String name();
	public native void name(java.lang.String name);
//	public native !UNKNOWN! name22();
//	public native void name3(!UNKNOWN! p1);
	public native void registerOnNameChange(Function0 handler);

	private native void _init();
	private native void _init(java.lang.String id, java.lang.String name);
	protected Contact(Nop nop) { super(nop); }
	static { System.loadLibrary("chatlib"); }
}
