// Generated by Scapix Language Bridge
// https://www.scapix.com

package com.scapix.chat;

public class Element extends AbstructElement
{
	public Element() { super(nop); _init(); }

	public native void func1();
	public native void func2(Contact p1);

	private native void _init();
	protected Element(Nop nop) { super(nop); }
	static { System.loadLibrary("chatlib"); }
}
