// Generated by Scapix Language Bridge
// https://www.scapix.com

package com.scapix.chat;

public class Model extends com.scapix.Bridge
{
	public Model() { super(nop); _init(); }

	public native void connect(java.lang.String id, java.lang.String password);
	public native void disconnect();
	public native Contact[] friends();
	public native Contact[] friends(java.lang.String filter);
	public native void addFriend(Contact contact);
	public native void removeFriend(Contact contact);
	public native Session[] sessions();
	public native Session sessionWithContact(Contact contact);

	private native void _init();
	protected Model(Nop nop) { super(nop); }
	static { System.loadLibrary("chatlib"); }
}
