// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <scapix/bridge/python/init.h>
#include <chat/folder/abstruct_element.h>

void scapix_python_export_abstruct_element(pybind11::module& m)
{
	pybind11::class_<chat::folder::abstruct_element, std::shared_ptr<chat::folder::abstruct_element>>(m, "AbstructElement")
		.def<void(chat::folder::abstruct_element::*)()>("func1", &chat::folder::abstruct_element::func1)
		.def<void(chat::folder::abstruct_element::*)()>("func2", &chat::folder::abstruct_element::func2)
		.def<void(chat::folder::abstruct_element::*)()>("func3", &chat::folder::abstruct_element::func3)
	;
}
