// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <scapix/bridge/python/init.h>
#include <chat/folder/element.h>

void scapix_python_export_element(pybind11::module& m)
{
	pybind11::class_<chat::folder::element, chat::folder::abstruct_element, std::shared_ptr<chat::folder::element>>(m, "Element")
		.def(pybind11::init<>())
		.def<void(chat::folder::element::*)()>("func1", &chat::folder::element::func1)
		.def<void(chat::folder::element::*)(std::shared_ptr<chat::contact>)>("func2", &chat::folder::element::func2)
	;
}
