// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <scapix/bridge/java/init.h>
#include <chat/folder/abstruct_element.h>

namespace scapix {
namespace link {
namespace java {

template <>
struct class_name<chat::folder::abstruct_element>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/AbstructElement");
};

} // namespace java
} // namespace link
} // namespace scapix

void scapix_java_export_abstruct_element()
{
	scapix::link::java::native_methods
	<
		scapix::link::java::class_name_t<chat::folder::abstruct_element>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("func1"),
			void(),
			void(chat::folder::abstruct_element::*)(),
			&chat::folder::abstruct_element::func1
		>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("func2"),
			void(),
			void(chat::folder::abstruct_element::*)(),
			&chat::folder::abstruct_element::func2
		>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("func3"),
			void(),
			void(chat::folder::abstruct_element::*)(),
			&chat::folder::abstruct_element::func3
		>
	>::register_();
}
