// Generated by Scapix Language Bridge

#include "contact.h"
#include "session.h"
#include "model.h"

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved)
{
  try
  {
    auto result = scapix::bridge::java::on_load(vm, reserved);

    chat::generated::contact_methods::register_();
    chat::generated::session_methods::register_();
    chat::generated::model_methods::register_();

    return result;
  }
  catch (const scapix::link::java::vm_exception& e)
  {
    e.get()->throw_();
  }

  return 0;
}
