// Generated by Scapix Language Bridge
// https://www.scapix.com

#pragma once
#include <chat/contact.h>

namespace scapix {
namespace link {
namespace java {

template <>
struct class_name<chat::contact>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/Contact");
};

} // namespace java
} // namespace link
} // namespace scapix
