// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <scapix/bridge/java/init.h>
#include <chat/extended_contact.h>

namespace scapix {
namespace link {
namespace java {

template <>
struct class_name<chat::extended_contact>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/ExtendedContact");
};

template <>
struct class_name<chat::extended_contact2>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/ExtendedContact2");
};

template <>
struct class_name<chat::extended_contact3>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/ExtendedContact3");
};

template <>
struct class_name<chat::contact>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/Contact");
};

} // namespace java
} // namespace link
} // namespace scapix

void scapix_java_export_extended_contact()
{
	scapix::link::java::native_methods
	<
		scapix::link::java::class_name_t<chat::extended_contact>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("_init"),
			void(scapix::link::java::ref<SCAPIX_META_STRING("java/lang/String")>, scapix::link::java::ref<SCAPIX_META_STRING("java/lang/String")>),
			void(scapix::bridge::java::init<chat::extended_contact>::*)(const std::basic_string<char> &, const std::basic_string<char> &),
			&scapix::bridge::java::init<chat::extended_contact>::create
		>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("_init"),
			void(jint),
			void(scapix::bridge::java::init<chat::extended_contact>::*)(int),
			&scapix::bridge::java::init<chat::extended_contact>::create
		>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("_init"),
			void(),
			void(scapix::bridge::java::init<chat::extended_contact>::*)(),
			&scapix::bridge::java::init<chat::extended_contact>::create
		>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("test"),
			void(scapix::link::java::ref<SCAPIX_META_STRING("java/lang/String")>, scapix::link::java::ref<SCAPIX_META_STRING("com/scapix/chat/Contact")>, scapix::link::java::ref<SCAPIX_META_STRING("com/scapix/chat/ExtendedContact")>),
			void(chat::extended_contact::*)(std::basic_string<char>, std::shared_ptr<chat::contact>, std::shared_ptr<chat::extended_contact>),
			&chat::extended_contact::test
		>
	>::register_();

	scapix::link::java::native_methods
	<
		scapix::link::java::class_name_t<chat::extended_contact2>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("_init"),
			void(),
			void(scapix::bridge::java::init<chat::extended_contact2>::*)(),
			&scapix::bridge::java::init<chat::extended_contact2>::create
		>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("test"),
			void(),
			void(chat::extended_contact2::*)(),
			&chat::extended_contact2::test
		>
	>::register_();

	scapix::link::java::native_methods
	<
		scapix::link::java::class_name_t<chat::extended_contact3>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("_init"),
			void(),
			void(scapix::bridge::java::init<chat::extended_contact3>::*)(),
			&scapix::bridge::java::init<chat::extended_contact3>::create
		>,

		scapix::link::java::native_method
		<
			SCAPIX_META_STRING("test"),
			void(),
			void(chat::extended_contact3::*)(),
			&chat::extended_contact3::test
		>
	>::register_();
}
