// Generated by Scapix Language Bridge
// https://www.scapix.com

#pragma once
#include <chat/model.h>

namespace scapix {
namespace link {
namespace java {

template <>
struct class_name<chat::model>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/Model");
};

} // namespace java
} // namespace link
} // namespace scapix
