// Generated by Scapix Language Bridge
// https://www.scapix.com

#pragma once
#include <chat/session.h>

namespace scapix {
namespace link {
namespace java {

template <>
struct class_name<chat::session>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/Session");
};

template <>
struct class_name<chat::session2>
{
	using type = SCAPIX_META_STRING("com/scapix/chat/Session2");
};

} // namespace java
} // namespace link
} // namespace scapix
