// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <chat/folder/abstruct_element.h>
#import "AbstructElement.h"

@implementation AbstructElement

-(void)func1
{
	return scapix::bridge::objc::call<void(chat::folder::abstruct_element::*)(), &chat::folder::abstruct_element::func1, void>(self);
}

-(void)func2
{
	return scapix::bridge::objc::call<void(chat::folder::abstruct_element::*)(), &chat::folder::abstruct_element::func2, void>(self);
}

-(void)func3
{
	return scapix::bridge::objc::call<void(chat::folder::abstruct_element::*)(), &chat::folder::abstruct_element::func3, void>(self);
}

@end
