// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface AbstructElement : BridgeObject

-(void)func1;
-(void)func2;
-(void)func3;

@end

NS_ASSUME_NONNULL_END
