// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface Contact : BridgeObject

-(instancetype)init;
-(instancetype)initWithId:(NSString*)id name:(NSString*)name;

-(NSString*)deviceName;
-(NSString*)id;
-(void)id:(NSString*)id;
-(NSString*)name;
-(void)name:(NSString*)name;
//-(!UNKNOWN!)name22;
//-(void)name3:(!UNKNOWN!)p1;
-(void)registerOnNameChange:(void(^)(NSString*))handler;

@end

NS_ASSUME_NONNULL_END
