// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "AbstructElement.h"

NS_ASSUME_NONNULL_BEGIN

@class Contact;

@interface Element : AbstructElement

-(instancetype)init;

-(void)func1;
-(void)func2:(Contact*)p1;

@end

NS_ASSUME_NONNULL_END
