// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "Contact.h"

NS_ASSUME_NONNULL_BEGIN

@class ExtendedContact2;
@class ExtendedContact3;

@interface ExtendedContact : Contact

-(instancetype)initWithId:(NSString*)id name:(NSString*)name;
-(instancetype)initWithP1:(int)p1;
-(instancetype)init;

-(void)test:(NSString*)p1 p2:(Contact*)p2 p3:(ExtendedContact*)p3;

@end

@interface ExtendedContact2 : ExtendedContact

-(instancetype)init;

-(void)test;

@end

@interface ExtendedContact3 : Contact

-(instancetype)init;

-(void)test;

@end

NS_ASSUME_NONNULL_END
