// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class Contact;
@class Session;
@class Session2;

@interface Model : BridgeObject

-(instancetype)init;

-(void)connect:(NSString*)id password:(NSString*)password;
-(void)disconnect;
-(NSArray<Contact*>*)friends;
-(NSArray<Contact*>*)friends:(NSString*)filter;
-(void)addFriend:(Contact*)contact;
-(void)removeFriend:(Contact*)contact;
-(NSArray<Session*>*)sessions;
-(Session*)sessionWithContact:(Contact*)contact;

@end

NS_ASSUME_NONNULL_END
