// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <scapix/bridge/js/init.h>
#include <chat/folder/abstruct_element.h>

EMSCRIPTEN_BINDINGS(scapix_abstruct_element)
{
	emscripten::class_<chat::folder::abstruct_element>("AbstructElement")
		.smart_ptr<std::shared_ptr<chat::folder::abstruct_element>>("shared_ptr<chat::folder::abstruct_element>")
		.function("func1", scapix::link::js::function<void(chat::folder::abstruct_element::*)(), &chat::folder::abstruct_element::func1>::select<>::func)
		.function("func2", scapix::link::js::function<void(chat::folder::abstruct_element::*)(), &chat::folder::abstruct_element::func2>::select<>::func)
		.function("func3", scapix::link::js::function<void(chat::folder::abstruct_element::*)(), &chat::folder::abstruct_element::func3>::select<>::func)
	;
}
