// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <scapix/bridge/js/init.h>
#include <chat/contact.h>

EMSCRIPTEN_BINDINGS(scapix_contact)
{
	emscripten::class_<chat::contact>("Contact")
		.smart_ptr<std::shared_ptr<chat::contact>>("shared_ptr<chat::contact>")
		.constructor(&std::make_shared<chat::contact>)
		.constructor(&std::make_shared<chat::contact, const std::basic_string<char> &, const std::basic_string<char> &>)
		.function("deviceName", scapix::link::js::function<std::basic_string<char>(chat::contact::*)() const, &chat::contact::device_name>::select<>::func)
		.function("id", scapix::link::js::function<const std::basic_string<char> &(chat::contact::*)(), &chat::contact::id>::select<>::func)
		.function("id", scapix::link::js::function<void(chat::contact::*)(const std::basic_string<char> &), &chat::contact::id>::select<>::func)
		.function("name", scapix::link::js::function<const std::basic_string<char> &(chat::contact::*)(), &chat::contact::name>::select<>::func)
		.function("name", scapix::link::js::function<void(chat::contact::*)(const std::basic_string<char> &), &chat::contact::name>::select<>::func)
		.function("registerOnNameChange", scapix::link::js::function<void(chat::contact::*)(std::function<void (std::basic_string<char>)>), &chat::contact::register_on_name_change>::select<>::func)
	;
}
