// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <scapix/bridge/js/init.h>
#include <chat/folder/element.h>

EMSCRIPTEN_BINDINGS(scapix_element)
{
	emscripten::class_<chat::folder::element, emscripten::base<chat::folder::abstruct_element>>("Element")
		.smart_ptr<std::shared_ptr<chat::folder::element>>("shared_ptr<chat::folder::element>")
		.constructor(&std::make_shared<chat::folder::element>)
		.function("func1", scapix::link::js::function<void(chat::folder::element::*)(), &chat::folder::element::func1>::select<>::func)
		.function("func2", scapix::link::js::function<void(chat::folder::element::*)(std::shared_ptr<chat::contact>), &chat::folder::element::func2>::select<>::func)
	;
}
