// Generated by Scapix Language Bridge
// https://www.scapix.com

#include <scapix/bridge/js/init.h>
#include <chat/model.h>

EMSCRIPTEN_BINDINGS(scapix_model)
{
	emscripten::class_<chat::model>("Model")
		.smart_ptr<std::shared_ptr<chat::model>>("shared_ptr<chat::model>")
		.constructor(&std::make_shared<chat::model>)
		.function("connect", scapix::link::js::function<void(chat::model::*)(std::basic_string<char>, std::basic_string<char>), &chat::model::connect>::select<>::func)
		.function("disconnect", scapix::link::js::function<void(chat::model::*)(), &chat::model::disconnect>::select<>::func)
		.function("friends", scapix::link::js::function<const std::vector<std::shared_ptr<chat::contact>, std::allocator<std::shared_ptr<chat::contact> > > &(chat::model::*)(), &chat::model::friends>::select<>::func)
		.function("friends", scapix::link::js::function<std::vector<std::shared_ptr<chat::contact>, std::allocator<std::shared_ptr<chat::contact> > >(chat::model::*)(std::basic_string<char>), &chat::model::friends>::select<>::func)
		.function("addFriend", scapix::link::js::function<void(chat::model::*)(std::shared_ptr<chat::contact>), &chat::model::add_friend>::select<>::func)
		.function("removeFriend", scapix::link::js::function<void(chat::model::*)(std::shared_ptr<chat::contact>), &chat::model::remove_friend>::select<>::func)
		.function("sessions", scapix::link::js::function<const std::vector<std::shared_ptr<chat::session>, std::allocator<std::shared_ptr<chat::session> > > &(chat::model::*)(), &chat::model::sessions>::select<>::func)
		.function("sessionWithContact", scapix::link::js::function<std::shared_ptr<chat::session>(chat::model::*)(std::shared_ptr<chat::contact>), &chat::model::session_with_contact>::select<>::func)
	;
}
